/*
 * To change this license header, choose License Headers in Project Properties.
 * To chang this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fabricacuscuz.interfaces;

import fabricacuscuz.UIFabrica;
import java.util.ArrayList;
import fabricacuscuz.Produto;

/**
 *
 * @author Beatriz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    UIFabrica fabrica = new UIFabrica();
    ArrayList<Produto> produtos = new ArrayList();
    


    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InternalTela = new javax.swing.JInternalFrame();
        labelFundoo = new javax.swing.JLabel();
        BotaoSairTelaInternal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        ItemCproduto = new javax.swing.JMenuItem();
        MenuEstoque = new javax.swing.JMenu();
        itemTodosProdutos = new javax.swing.JRadioButtonMenuItem();
        itemProdutosDisponiveis = new javax.swing.JRadioButtonMenuItem();
        MenuFerramentas = new javax.swing.JMenu();
        itemReceitas = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        itemSairtudo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InternalTela.setTitle("Bem vindo");
        InternalTela.setVisible(true);

        labelFundoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/fundo-de-linhas-de-zoom-em-quadrinhos-amarelo_1017-15136.jpg"))); // NOI18N
        labelFundoo.setText("jLabel1");
        InternalTela.getContentPane().add(labelFundoo, java.awt.BorderLayout.CENTER);

        BotaoSairTelaInternal.setText("Sair");
        BotaoSairTelaInternal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairTelaInternalActionPerformed(evt);
            }
        });
        InternalTela.getContentPane().add(BotaoSairTelaInternal, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        InternalTela.getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(InternalTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/fundo-de-linhas-de-zoom-em-quadrinhos-amarelo_1017-15136.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        MenuCadastro.setText("Cadastro");

        ItemCproduto.setText("Produto");
        ItemCproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCprodutoActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemCproduto);

        jMenuBar1.add(MenuCadastro);

        MenuEstoque.setText("Estoque");

        itemTodosProdutos.setSelected(true);
        itemTodosProdutos.setText("Todos Produtos");
        itemTodosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTodosProdutosActionPerformed(evt);
            }
        });
        MenuEstoque.add(itemTodosProdutos);

        itemProdutosDisponiveis.setSelected(true);
        itemProdutosDisponiveis.setText("Produtos Disponiveis");
        itemProdutosDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutosDisponiveisActionPerformed(evt);
            }
        });
        MenuEstoque.add(itemProdutosDisponiveis);

        jMenuBar1.add(MenuEstoque);

        MenuFerramentas.setText("Ferramentas");

        itemReceitas.setText("Receitas");
        itemReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReceitasActionPerformed(evt);
            }
        });
        MenuFerramentas.add(itemReceitas);

        jMenuBar1.add(MenuFerramentas);

        menuSair.setText("Sair");

        itemSairtudo.setText("Fechar tudo");
        itemSairtudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairtudoActionPerformed(evt);
            }
        });
        menuSair.add(itemSairtudo);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCprodutoActionPerformed
        telaCadastrarProduto telacadastrar = new telaCadastrarProduto();
        telacadastrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_ItemCprodutoActionPerformed

    private void BotaoSairTelaInternalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairTelaInternalActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotaoSairTelaInternalActionPerformed

    private void itemReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReceitasActionPerformed
        TelaReceitas  tela = new TelaReceitas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemReceitasActionPerformed

    private void itemSairtudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairtudoActionPerformed
        dispose();
    }//GEN-LAST:event_itemSairtudoActionPerformed

    private void itemTodosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTodosProdutosActionPerformed
       for(Produto produto: produtos){
           System.out.println(produtos);
       }
    }//GEN-LAST:event_itemTodosProdutosActionPerformed

    private void itemProdutosDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutosDisponiveisActionPerformed
        for(Produto produto: produtos){
            if(produto.isDisponivel()){
            System.out.println(produto.getNome());
            }
        }
    }//GEN-LAST:event_itemProdutosDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSairTelaInternal;
    private javax.swing.JInternalFrame InternalTela;
    private javax.swing.JMenuItem ItemCproduto;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuEstoque;
    private javax.swing.JMenu MenuFerramentas;
    private javax.swing.JRadioButtonMenuItem itemProdutosDisponiveis;
    private javax.swing.JMenuItem itemReceitas;
    private javax.swing.JMenuItem itemSairtudo;
    private javax.swing.JRadioButtonMenuItem itemTodosProdutos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelFundoo;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables

}
