/*
 * To change this license header, choose License Headers in Project Properties.
 * To chang this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fabricacuscuz.interfaces;



/**
 *
 * @author Beatriz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    


    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        ItemCproduto = new javax.swing.JMenuItem();
        venda = new javax.swing.JMenuItem();
        MenuFerramentas = new javax.swing.JMenu();
        itemReceitas = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        itemSairtudo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/logopratelaprincipal-Recuperado.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        MenuCadastro.setText("Cadastro");

        ItemCproduto.setText("Produto");
        ItemCproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCprodutoActionPerformed(evt);
            }
        });
        MenuCadastro.add(ItemCproduto);

        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        MenuCadastro.add(venda);

        jMenuBar1.add(MenuCadastro);

        MenuFerramentas.setText("Ferramentas");

        itemReceitas.setText("Receitas");
        itemReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReceitasActionPerformed(evt);
            }
        });
        MenuFerramentas.add(itemReceitas);

        jMenuBar1.add(MenuFerramentas);

        menuSair.setText("Sair");

        itemSairtudo.setText("Fechar tudo");
        itemSairtudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairtudoActionPerformed(evt);
            }
        });
        menuSair.add(itemSairtudo);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemCprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCprodutoActionPerformed
        telaCadastrarProduto telacadastrar = new telaCadastrarProduto();
        telacadastrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_ItemCprodutoActionPerformed

    private void itemReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReceitasActionPerformed
        TelaReceitas  tela = new TelaReceitas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemReceitasActionPerformed

    private void itemSairtudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairtudoActionPerformed
        dispose();
    }//GEN-LAST:event_itemSairtudoActionPerformed

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        // TODO add your handling code here:
        new RegistroVenda().setVisible(true);
        dispose();
    }//GEN-LAST:event_vendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCproduto;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuFerramentas;
    private javax.swing.JMenuItem itemReceitas;
    private javax.swing.JMenuItem itemSairtudo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem venda;
    // End of variables declaration//GEN-END:variables

}
