/*
 * To change this license header, choose License Headers in Project Properties.
 * To chang this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fabricacuscuz.interfaces;

import static java.awt.Frame.MAXIMIZED_BOTH;



/**
 *
 * @author Beatriz
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    


    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botavenda = new javax.swing.JButton();
        botaReceita = new javax.swing.JButton();
        cadastrarproduto = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        registrarvenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botavenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/registrarvendabotao.jpg"))); // NOI18N
        botavenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botavenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botavendaActionPerformed(evt);
            }
        });
        getContentPane().add(botavenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 170, 60));

        botaReceita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoregistrarreceita.jpg"))); // NOI18N
        botaReceita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaReceitaActionPerformed(evt);
            }
        });
        getContentPane().add(botaReceita, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 170, 60));

        cadastrarproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaocadastrarproduto.jpg"))); // NOI18N
        cadastrarproduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cadastrarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 170, 60));

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/icon (1).png"))); // NOI18N
        sair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 40, 40));

        registrarvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoregistrarcompra.jpg"))); // NOI18N
        registrarvenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registrarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarvendaActionPerformed(evt);
            }
        });
        getContentPane().add(registrarvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/telaprincipal_3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarprodutoActionPerformed
        // TODO add your handling code here:
        new telaCadastrarProduto().setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarprodutoActionPerformed

    private void botavendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botavendaActionPerformed
        // TODO add your handling code here:
        new RegistroVenda().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botavendaActionPerformed

    private void botaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaReceitaActionPerformed
        // TODO add your handling code here:
        new TelaReceitas().setVisible(true);
        dispose();
    }//GEN-LAST:event_botaReceitaActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void registrarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarvendaActionPerformed
        // TODO add your handling code here:
        new compra().setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarvendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaReceita;
    private javax.swing.JButton botavenda;
    private javax.swing.JButton cadastrarproduto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarvenda;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables

}
