/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabricacuscuz.interfaces;

import connection.ProdutoDAO;
import fabricacuscuz.dominio.Produto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import fabricacuscuz.interfaces.TelaPrincipal;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Beatriz
 */
public class telaCadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastrarProduto
     */
    public telaCadastrarProduto() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(dtm));
        readJTable();
    }

    public void readJTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto produto : dao.read()){
            dtm.addRow(new Object[]{
                produto.getId(),
                produto.getFuncionario(),
                produto.getDescricao(),
                produto.getPreco(),
                produto.getQuantidade(),
                produto.getCategoria(),
                produto.getFornecedor()
                    
            });
            
            
        }
    }
    public void readjTableForDesc(String desc){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto produto : dao.readForDesc(desc)){
            dtm.addRow(new Object[]{
                produto.getId(),
                produto.getFuncionario(),
                produto.getDescricao(),
                produto.getPreco(),
                produto.getQuantidade(),
                produto.getCategoria(),
                produto.getFornecedor()
                    
            });
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPreco = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtFuncionario = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        botaoCadastrarP = new javax.swing.JButton();
        botaoSairTelaC = new javax.swing.JButton();
        labelConcluido = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        jTableProduto = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoExcluir = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtFornecedor = new javax.swing.JTextField();
        txtBusca = new javax.swing.JTextField();
        botaoBuscar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco);
        txtPreco.setBounds(1130, 150, 110, 30);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(550, 150, 220, 30);

        txtFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuncionario);
        txtFuncionario.setBounds(200, 150, 150, 30);

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(930, 150, 80, 30);

        botaoCadastrarP.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastrarP.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        botaoCadastrarP.setForeground(new java.awt.Color(255, 204, 0));
        botaoCadastrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaocadastrar.jpg"))); // NOI18N
        botaoCadastrarP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrarP);
        botaoCadastrarP.setBounds(1140, 510, 160, 40);

        botaoSairTelaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/left-pointing-arrow.png"))); // NOI18N
        botaoSairTelaC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoSairTelaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairTelaCActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSairTelaC);
        botaoSairTelaC.setBounds(1280, 20, 40, 40);

        labelConcluido.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        labelConcluido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelConcluido);
        labelConcluido.setBounds(80, 640, 120, 40);
        getContentPane().add(labelID);
        labelID.setBounds(100, 514, 110, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "FUNCIONARIO", "DESCRIÇÃO", "PREÇO", "QUANTIDADE", "CATEGORIA", "FORNECEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("CADASTRO DE PRODUTOS");
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jTableProduto.setViewportView(jTable1);

        getContentPane().add(jTableProduto);
        jTableProduto.setBounds(60, 270, 1010, 500);

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoexluir.jpg"))); // NOI18N
        botaoExcluir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(1140, 340, 170, 40);

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoatualizar_1.jpg"))); // NOI18N
        botaoAtualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAtualizar);
        botaoAtualizar.setBounds(1140, 430, 170, 40);
        getContentPane().add(txtCategoria);
        txtCategoria.setBounds(180, 180, 170, 30);
        getContentPane().add(txtFornecedor);
        txtFornecedor.setBounds(520, 180, 320, 30);

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBusca);
        txtBusca.setBounds(860, 220, 230, 30);

        botaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/buscar.jpg"))); // NOI18N
        botaoBuscar.setText("jButton1");
        botaoBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscar);
        botaoBuscar.setBounds(1100, 210, 150, 40);

        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/cadastroproduto_1.jpg"))); // NOI18N
        fundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fundo);
        fundo.setBounds(0, -30, 1430, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed

    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed

    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed

    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuncionarioActionPerformed


    }//GEN-LAST:event_txtFuncionarioActionPerformed

    private void botaoCadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPActionPerformed
        
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        p.setFuncionario(txtFuncionario.getText());
        p.setDescricao(txtDescricao.getText());
        p.setPreco(Double.parseDouble(txtPreco.getText()));
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        p.setCategoria(txtCategoria.getText());
        p.setFornecedor(txtFornecedor.getText());

        try {
            dao.salvar(p);
            readJTable();
            txtFuncionario.setText("");
            txtDescricao.setText("");
            txtPreco.setText("");
            txtQuantidade.setText("");
            txtCategoria.setText("");
            txtFornecedor.setText("");
            
           
        } catch (SQLException ex) {
            Logger.getLogger(telaCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

//        if(txtNome.getText().equals("") && txtQuantidade.getText().equals("") && txtPreco.getText().equals("")
//       && txtDescricao.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha os campos!!");
// }
// if(txtNome.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo NOME");
//}else if(txtQuantidade.getText().equals("")){
//  JOptionPane.showMessageDialog(null, "Preencha o campo QUANTIDADE");
// }else if(txtPreco.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo PREÇO");
// }else if(txtDescricao.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo DESCRIÇÃO");
/// }
// labelConcluido.setText("Cadastro Concluído!");

    }//GEN-LAST:event_botaoCadastrarPActionPerformed

    private void botaoSairTelaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairTelaCActionPerformed
        TelaPrincipal telap = new TelaPrincipal();
        telap.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoSairTelaCActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
 if(jTable1.getSelectedRow() != -1){
       
   
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
       
p.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        dao.apagar(p);
       
        txtFuncionario.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        txtCategoria.setText("");
        txtFornecedor.setText("");
        readJTable(); 
 }else{
     JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
 }
    
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
   if(jTable1.getSelectedRow() != -1){
       
   if(txtFuncionario.getText().equals("") || txtDescricao.getText().equals("") || txtPreco.getText().equals("") || 
           txtQuantidade.getText().equals("") || txtCategoria.getText().equals("") || txtFornecedor.getText().equals("")){
       JOptionPane.showMessageDialog(null, "Por favor, preencha os campos");
   }
   }else{
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();       
        p.setFuncionario(txtFuncionario.getText());
        p.setDescricao(txtDescricao.getText());
        p.setPreco(Double.parseDouble(txtPreco.getText()));
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        p.setCategoria(txtCategoria.getText());
        p.setFornecedor(txtFornecedor.getText());
        p.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        dao.alterar(p);
       
        txtFuncionario.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtQuantidade.setText("");
        txtCategoria.setText("");
        txtFornecedor.setText("");
        readJTable();   
        }
    

           
   
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

        if(jTable1.getSelectedRow() != -1){
            
            txtFuncionario.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
            txtDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
            txtPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
            txtQuantidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
            txtCategoria.setText(jTable1.getValueAt(jTable1.getSelectedRow(),5).toString());
            txtFornecedor.setText(jTable1.getValueAt(jTable1.getSelectedRow(),6).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        
        readjTableForDesc(txtBusca.getText());
        
    }//GEN-LAST:event_botaoBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoCadastrarP;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoSairTelaC;
    private javax.swing.JLabel fundo;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jTableProduto;
    private javax.swing.JLabel labelConcluido;
    private javax.swing.JLabel labelID;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
