/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fabricacuscuz.interfaces;

import connection.ProdutoDAO;
import fabricacuscuz.dominio.Produto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import fabricacuscuz.interfaces.TelaPrincipal;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Beatriz
 */
public class telaCadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastrarProduto
     */
    public telaCadastrarProduto() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        readJTable();
;
    }

    public void readJTable(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);
        ProdutoDAO dao = new ProdutoDAO();
        
        for(Produto produto : dao.read()){
            dtm.addRow(new Object[]{
                produto.getId(),
                produto.getNome(),
                produto.getDescricao(),
                produto.getPreco(),
                produto.getQuantidade()
            });
            
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPreco = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        botaoCadastrarP = new javax.swing.JButton();
        botaoSairTelaC = new javax.swing.JButton();
        labelConcluido = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        jTableProduto = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoExcluir = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreco);
        txtPreco.setBounds(160, 410, 90, 40);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(240, 320, 450, 40);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(150, 230, 300, 40);

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade);
        txtQuantidade.setBounds(270, 510, 70, 40);

        botaoCadastrarP.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastrarP.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        botaoCadastrarP.setForeground(new java.awt.Color(255, 204, 0));
        botaoCadastrarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaocadastrar.jpg"))); // NOI18N
        botaoCadastrarP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarPActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrarP);
        botaoCadastrarP.setBounds(260, 630, 160, 50);

        botaoSairTelaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/icon (1).png"))); // NOI18N
        botaoSairTelaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairTelaCActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSairTelaC);
        botaoSairTelaC.setBounds(1310, 10, 40, 40);

        labelConcluido.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        labelConcluido.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelConcluido);
        labelConcluido.setBounds(80, 640, 120, 40);
        getContentPane().add(labelID);
        labelID.setBounds(100, 514, 110, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DESCRIÇÃO", "PREÇO", "QUANTIDADE"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jTableProduto.setViewportView(jTable1);

        getContentPane().add(jTableProduto);
        jTableProduto.setBounds(800, 210, 550, 470);

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoexluir.jpg"))); // NOI18N
        botaoExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoExcluir);
        botaoExcluir.setBounds(440, 630, 180, 50);

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/botaoatualizar.jpg"))); // NOI18N
        botaoAtualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAtualizar);
        botaoAtualizar.setBounds(1200, 140, 140, 43);

        fundo.setForeground(new java.awt.Color(255, 255, 255));
        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fabricacuscuz/imagens/cadastrarprodutostelacheia.jpg"))); // NOI18N
        fundo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fundo);
        fundo.setBounds(0, -10, 1430, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed

    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed

    }//GEN-LAST:event_txtPrecoActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed

    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed


    }//GEN-LAST:event_txtNomeActionPerformed

    private void botaoCadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarPActionPerformed
        
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        
        p.setNome(txtNome.getText());
        p.setDescricao(txtDescricao.getText());
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        p.setPreco(Double.parseDouble(txtPreco.getText()));

        try {
            dao.salvar(p);
            readJTable();
            txtNome.setText("");
            txtDescricao.setText("");
            txtPreco.setText("");
            txtQuantidade.setText("");
            
           
        } catch (SQLException ex) {
            Logger.getLogger(telaCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

//        if(txtNome.getText().equals("") && txtQuantidade.getText().equals("") && txtPreco.getText().equals("")
//       && txtDescricao.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha os campos!!");
// }
// if(txtNome.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo NOME");
//}else if(txtQuantidade.getText().equals("")){
//  JOptionPane.showMessageDialog(null, "Preencha o campo QUANTIDADE");
// }else if(txtPreco.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo PREÇO");
// }else if(txtDescricao.getText().equals("")){
// JOptionPane.showMessageDialog(null, "Preencha o campo DESCRIÇÃO");
/// }
// labelConcluido.setText("Cadastro Concluído!");

    }//GEN-LAST:event_botaoCadastrarPActionPerformed

    private void botaoSairTelaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairTelaCActionPerformed
        TelaPrincipal telap = new TelaPrincipal();
        telap.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoSairTelaCActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed


    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
if(jTable1.getSelectedRow() != -1){
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();  
       
        p.setNome(txtNome.getText());
        p.setDescricao(txtDescricao.getText());
        p.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        p.setPreco(Double.parseDouble(txtPreco.getText()));
  
       

       
    try {
        dao.update(p);
        dao.salvar(p);
    } catch (SQLException ex) {
        Logger.getLogger(telaCadastrarProduto.class.getName()).log(Level.SEVERE, null, ex);
    }
       txtNome.setText("");
       txtDescricao.setText("");
       txtPreco.setText("");
       txtQuantidade.setText("");
       readJTable();
           
           
           
}
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

        if(jTable1.getSelectedRow() != -1){
            
            txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
            txtDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
            txtPreco.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
            txtQuantidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrarP;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoSairTelaC;
    private javax.swing.JLabel fundo;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jTableProduto;
    private javax.swing.JLabel labelConcluido;
    private javax.swing.JLabel labelID;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
